Upload Student Profile
frankibem/UniWatch pull request #14
Opened 2016-11-26 22:18 UTC by the-pat

Added functionality for upload student profile

2016-11-26 23:06 UTC, frankibem requested changes
Minor change required. It's not showing an error when you don't select an image (see comment)

2016-11-26 23:06 UTC, frankibem commented on UniWatch/Controllers/StudentController.cs
> +            if (!files.Any())
I hit the upload button without selecting any images and this was bypassed. The list had a single null entry so the condition was false. Can you update this and LectureController as well. i.e. if you don't select an image, files.Count == 1 and files.ElementAt(0) == null. It's supposed to send you back to that page with the error "No file selected"

2016-11-26 23:43 UTC, the-pat commented on UniWatch/Controllers/StudentController.cs
> +            if (!files.Any())
Resolved

2016-11-27 01:26 UTC, frankibem approved these changes

2016-11-27 01:26 UTC, merged